# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.spinBoxPort = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxPort.setGeometry(QtCore.QRect(360, 10, 42, 22))
        self.spinBoxPort.setMaximum(65536)
        self.spinBoxPort.setProperty("value", 502)
        self.spinBoxPort.setObjectName("spinBoxPort")
        self.pushButtonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonConnect.setGeometry(QtCore.QRect(420, 10, 75, 23))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.pushButtonDisConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDisConnect.setGeometry(QtCore.QRect(510, 10, 75, 23))
        self.pushButtonDisConnect.setObjectName("pushButtonDisConnect")
        self.comboBoxIP = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxIP.setGeometry(QtCore.QRect(190, 10, 121, 22))
        self.comboBoxIP.setEditable(True)
        self.comboBoxIP.setObjectName("comboBoxIP")
        self.groupBoxCoils = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxCoils.setGeometry(QtCore.QRect(30, 40, 741, 101))
        self.groupBoxCoils.setObjectName("groupBoxCoils")
        self.groupBoxHoldingRegisters = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxHoldingRegisters.setGeometry(QtCore.QRect(30, 160, 741, 101))
        self.groupBoxHoldingRegisters.setObjectName("groupBoxHoldingRegisters")
        self.groupBoxHoldingRegisters_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxHoldingRegisters_2.setGeometry(QtCore.QRect(410, 280, 361, 101))
        self.groupBoxHoldingRegisters_2.setObjectName("groupBoxHoldingRegisters_2")
        self.groupBoxHoldingRegisters_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxHoldingRegisters_3.setGeometry(QtCore.QRect(40, 270, 361, 291))
        self.groupBoxHoldingRegisters_3.setObjectName("groupBoxHoldingRegisters_3")
        self.widget = QtWidgets.QWidget(self.groupBoxHoldingRegisters_3)
        self.widget.setGeometry(QtCore.QRect(50, 40, 258, 223))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonSetInputRegisters = QtWidgets.QPushButton(self.widget)
        self.pushButtonSetInputRegisters.setObjectName("pushButtonSetInputRegisters")
        self.gridLayout.addWidget(self.pushButtonSetInputRegisters, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "plc调试程序"))
        self.label.setText(_translate("MainWindow", "IP地址："))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.pushButtonConnect.setText(_translate("MainWindow", "连接"))
        self.pushButtonDisConnect.setText(_translate("MainWindow", "断开连接"))
        self.comboBoxIP.setCurrentText(_translate("MainWindow", "127.0.0.1"))
        self.groupBoxCoils.setTitle(_translate("MainWindow", "读写线圈"))
        self.groupBoxHoldingRegisters.setTitle(_translate("MainWindow", "读写保持寄存器"))
        self.groupBoxHoldingRegisters_2.setTitle(_translate("MainWindow", "读取离散输入寄存器"))
        self.groupBoxHoldingRegisters_3.setTitle(_translate("MainWindow", "读取连续输入寄存器"))
        self.pushButtonSetInputRegisters.setText(_translate("MainWindow", "设置"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())