# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 54, 12))
        self.label.setObjectName("label")
        self.lineEdit_IP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_IP.setGeometry(QtCore.QRect(190, 10, 113, 20))
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.spinBoxPort = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxPort.setGeometry(QtCore.QRect(360, 10, 42, 22))
        self.spinBoxPort.setMaximum(65536)
        self.spinBoxPort.setProperty("value", 502)
        self.spinBoxPort.setObjectName("spinBoxPort")
        self.pushButtonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonConnect.setGeometry(QtCore.QRect(420, 10, 75, 23))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.pushButtonConnect.clicked.connect(self.connect)
        self.pushButtonConnect.setEnabled(True)

        self.pushButtonDisConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDisConnect.setGeometry(QtCore.QRect(510, 10, 75, 23))
        self.pushButtonDisConnect.setObjectName("pushButtonDisConnect")
        self.pushButtonDisConnect.clicked.connect(self.disConnect)
        self.pushButtonDisConnect.setEnabled(False)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "plc调试程序"))
        self.label.setText(_translate("MainWindow", "IP地址："))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.pushButtonConnect.setText(_translate("MainWindow", "连接"))
        self.pushButtonDisConnect.setText(_translate("MainWindow", "断开连接"))

    def connect(self):
        self.setCltStatusWhenConnect()

    def disConnect(self):
        self.setCltStatusWhenDisConnect()

    def getIP(self):
        return self.lineEdit_IP.text()

    def getPort(self):
        return self.spinBoxPort.value()

    def setCltStatusWhenConnect(self):
        self.pushButtonConnect.setEnabled(False)
        self.pushButtonDisConnect.setEnabled(True)

    def setCltStatusWhenDisConnect(self):
        self.pushButtonConnect.setEnabled(True)
        self.pushButtonDisConnect.setEnabled(False)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
