# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setFixedSize(800, 600)
        MainWindow.setWindowFlags(Qt.WindowCloseButtonHint|Qt.WindowMinimizeButtonHint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.spinBoxPort = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxPort.setGeometry(QtCore.QRect(360, 10, 42, 22))
        self.spinBoxPort.setMaximum(65536)
        self.spinBoxPort.setProperty("value", 502)
        self.spinBoxPort.setObjectName("spinBoxPort")
        self.pushButtonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonConnect.setGeometry(QtCore.QRect(420, 10, 75, 23))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.pushButtonDisConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDisConnect.setGeometry(QtCore.QRect(510, 10, 75, 23))
        self.pushButtonDisConnect.setObjectName("pushButtonDisConnect")
        self.comboBoxIP = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxIP.setGeometry(QtCore.QRect(190, 10, 121, 22))
        self.comboBoxIP.setEditable(True)
        self.comboBoxIP.setObjectName("comboBoxIP")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 321, 171))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 50, 361, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.timer=QtCore.QTimer(MainWindow)
        self.timer.timeout.connect(self.showtime)
        self.timer.start(100)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "plc调试程序"))
        self.label.setText(_translate("MainWindow", "IP地址："))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.pushButtonConnect.setText(_translate("MainWindow", "连接"))
        self.pushButtonDisConnect.setText(_translate("MainWindow", "断开连接"))
        self.comboBoxIP.setCurrentText(_translate("MainWindow", "127.0.0.1"))
        self.groupBox.setTitle(_translate("MainWindow", "读写线圈"))
        self.groupBox_2.setTitle(_translate("MainWindow", "读写保持寄存器"))

    def showtime(self):
        datetime=QtCore.QDateTime.currentDateTime()
        text=datetime.toString("yyyy-MM-dd hh:mm:ss")
        self.statusBar.showMessage('当前时间：'+text+'',0)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())